const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const userSchema = new mongoose.Schema({
	husbandAadhar: { type: String},
    wifeAadhar: { type: String},
    husbandPassport: { type: String},
    wifePassport: { type: String},
    husbandDOI:{ type: String},
    husbandDOE:{ type: String},
    wifeDOI:{ type: String},
    wifeDOE:{ type: String},
	applicationId:{type:String},
	loginId: { type: String },
    loginName: { type: String },
	loginType:{type:String,default:'USER'},
    loginKey: { type: String },
    loginEmail: { type: String },
    loginMobile: { type: Number },
    loginPassword: { type: String },
	loginAttemptsLeft: { type: Number, default: 5 },
	loginBlockedUntil: { type: Date, default: null },
	husbandName: { type: String},
	husbandReligion: { type: String },
	husbandCaste: { type: String},
	husbandCastename:{type:String},
	status:{type:String},
	mrgType:{type:String},
	husBandAdharNum:{type:Number},
	husbandDateofBirth: {type: Date},
	husbandMobile: { type: Number },
	husbandMarriageAge: { type: Number },
	husbandCountry: { type: String },
	husbandState: { type: String},
	husbandAddress: { type: String },
	husbandPermanentAddress: { type: String },
	husbandFatherName: { type: String },
	husbandMotherName: { type: String },
	isHusbandDivorcee: { type: String },
	husbandDivorceDate: { type: Date },
	isHusbandWidower: { type: String},

	wifeAdharNum:{type:Number},
	wifeName: { type: String},
	wifeReligion:{ type: String },
	wifeCaste: { type: String},
	wifeDateofBirth: { type: Date},
	wifeMobile: { type: Number},
	wifeMarriageAge: { type: String},
	wifeCountry: { type: String},
	wifeOtherCountry: { type: String },
	wifeState: { type: String },
	wifeOtherState: { type: String },
	wifeAddress: { type: String },
	wifePermanentAddress: { type: String},
	wifeRelationship: { type: String },
	wifeFatherName: { type: String },
	wifeMotherName: { type: String },
	isWifeDivorcee:{ type: String },
	wifeDivorceDate: { type: Date },
	isWifeWidow: { type: String, },
	marriageDate: { type: Date},
	regDate: { type: Date},
	sroDistrict: { type: String },
	sroMandal: { type: String},
	sroOffice: { type: String },
	villageScretariatCode: { type: String },
    villageScretariatName: { type: String },
	husbandvillageScretariatName: { type: String },
    husbandvillageScretariatCode: { type: String },
	wifevillageScretariatName: { type: String },
    wifevillageScretariatCode: { type: String },
	seqenceNum:{type:String},
	slotTime: { type: String },
	certificateCopies: { type: Number },
	doc_wifePhoto: { type: Boolean, default: false },
	doc_husbandPhoto: { type: Boolean, default: false },
	doc_husbandAgeProof: { type: Boolean, default: false },
	doc_husbandAddressProof: { type: Boolean, default: false },
	doc_husbandSignature: { type: Boolean, default: false },
	doc_wifeAgeProof: { type: Boolean, default: false },
	doc_wifeAddressProof:{ type: Boolean, default: false },
	doc_wifeSignature: { type: Boolean, default: false },
	doc_husbandDivorce: { type: Boolean, default: false },
	doc_wifeDivorce: { type: Boolean, default: false },
	husbandOccupation: {type:String},
	husbandLengthofResidence: {type: Date},
	wifeOccupation: {type:String},
	wifeLengthofResidence: {type:Date},
	slotDate: {type:Date},
	placeOfMarriage: {type:String},
	issetToNotice:{type:Boolean,default:false},
	noticeSeqNumber:{type:Number},
	noticeStartDate:{type:Date},
	noticeEndDate:{type:Date},
	reasonForRejection:{type:String},
	actionDate:{type:Date},
	marriedAddress:{type:String},
	registrationAddress:{type:String},
	transactionID:{type:String},
	transactionAmount:{type:String},
	husbandDistrict:{type:String}, 
	wifeDistrict:{type:String},
	husbandMandal:{type:String},
	husbandVillage: {type: String},
	wifeVillage: {type: String},
	sroVillage: {type: String},
	wifeMandal:{type:String},
	husbandSroOffice:{type:String},
	husbandSroEmail:{type:String},
	wifeSroOffice:{type:String},
	wifeSroEmail:{type:String,},
	cert_form:{type:Boolean,default:false},
	cert_url:{type:String},
    cerSequence:{type:Number},
	sroNumber:{type:Number},
	lastLogin:{type: String},
	paymentMode: {type: String, default: ''},
	documents:[],
	husbandeSignAadhar:{ type: String, default: "" },
    wifeeSignAadhar:{ type: String, default: "" },
    witness1Aadhar: { type: String, default: "" },
    witness2Aadhar: { type: String, default: "" },
    witness3Aadhar: { type: String, default: "" },
    sroAadhar: { type: String, default: "" },
    witness1Name: { type: String, default: "" },
    witness2Name: { type: String, default: "" },
    witness3Name: { type: String, default: "" },
	srName:{ type: String, default: "" },
	husbandeSignStatus: { type: Boolean, default: false },
	wifeeSignStatus: { type: Boolean, default: false },
	witness1eSignStatus: { type: Boolean, default: false },
	witness2eSignStatus: { type: Boolean, default: false },
	witness3eSignStatus: { type: Boolean, default: false },
	sroeSignStatus: { type: Boolean, default: false },
	husbandeSignTranId:{ type: String, default: "" },
    wifeeSignTranId:{ type: String, default: "" },
    witness1eSignTranId: { type: String, default: "" },
    witness2eSignTranId: { type: String, default: "" },
    witness3eSignTranId: { type: String, default: "" },
    sroeSignTranId: { type: String, default: "" },
},{timestamps:true})


  





module.exports = mongoose.model("users", userSchema);
